server:
  port: 8081
spring:
  #autoconfigure:
  #  exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1
    driver-class-name: oracle.jdbc.OracleDriver
    username: EMPLOYEE
    password: dudkrish1A
    jpa:
      show-sql: true
      format-sql: true
      properties:
        hibernate:
          enable_lazy_load_no_trans: true
      database-platform: org.hibernate.dialect.Oracle12cDialect
  sql:
    init:
      continue-on-error: true

jwt:
  enabled: false
  secret: AvHGRK8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadweheufHNyG
  expirationMs: 86400000
  token:
    validity: 360000000 ##Expiration time in milliseconds 120 minutes
    issuer: hari.learning1989